[package]
name = "anime-matrix"
version = "0.1.0"
authors = ["Marcus"]
edition = "2018"

[dependencies]
rusb = "0.6"

rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["json", "serve"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
